name: Build and Push Docker Image

on:
  schedule:
    - cron: "0 0 * * 0" # Once per week, Sunday at midnight UTC
  workflow_dispatch: # Manual trigger if needed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout wrapper repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/shahram7/pdfextend:latest
